const jobs = [
  {
    company: 'Photosnap',
    logo: '/images/photosnap.svg',
    new: true,
    featured: true,
    position: 'Senior Frontend Developer',
    role: 'Frontend',
    level: 'Senior',
    postedAt: '1d ago',
    contract: 'Full Time',
    location: 'USA Only',
    languages: ['HTML', 'CSS', 'JavaScript'],
    tools: [],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 100000,
    salaryEnd: 200000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Manage',
    logo: '/images/manage.svg',
    new: true,
    featured: true,
    position: 'Fullstack Developer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '1d ago',
    contract: 'Part Time',
    location: 'Remote',
    languages: ['Python'],
    tools: ['React'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 100000,
    salaryEnd: 150000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Account',
    logo: '/images/account.svg',
    new: true,
    featured: false,
    position: 'Junior Frontend Developer',
    role: 'Frontend',
    level: 'Junior',
    postedAt: '2d ago',
    contract: 'Part Time',
    location: 'USA Only',
    languages: ['JavaScript'],
    tools: ['React', 'Sass'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 60000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'MyHome',
    logo: '/images/myhome.svg',
    new: false,
    featured: false,
    position: 'Junior Frontend Developer',
    role: 'Frontend',
    level: 'Junior',
    postedAt: '5d ago',
    contract: 'Contract',
    location: 'USA Only',
    languages: ['CSS', 'JavaScript'],
    tools: [],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 60000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Loop Studios',
    logo: '/images/loop-studios.svg',
    new: false,
    featured: false,
    position: 'Software Engineer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '1w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['JavaScript'],
    tools: ['Ruby', 'Sass'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 100000,
    salaryEnd: 200000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'FaceIt',
    logo: '/images/faceit.svg',
    new: false,
    featured: false,
    position: 'Junior Backend Developer',
    role: 'Backend',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'UK Only',
    languages: ['Ruby'],
    tools: ['RoR'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 70000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Shortly',
    logo: '/images/shortly.svg',
    new: false,
    featured: false,
    position: 'Junior Developer',
    role: 'Frontend',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['HTML', 'JavaScript'],
    tools: ['Sass'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 60000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Insure',
    logo: '/images/insure.svg',
    new: false,
    featured: false,
    position: 'Junior Frontend Developer',
    role: 'Frontend',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'USA Only',
    languages: ['JavaScript'],
    tools: ['Vue', 'Sass'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 60000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'Eyecam Co.',
    logo: '/images/eyecam-co.svg',
    new: false,
    featured: false,
    position: 'Full Stack Engineer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '3w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['JavaScript', 'Python'],
    tools: ['Django'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 100000,
    salaryEnd: 200000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
  {
    company: 'The Air Filter Company',
    logo: '/images/the-air-filter-company.svg',
    new: false,
    featured: false,
    position: 'Front-end Dev',
    role: 'Frontend',
    level: 'Junior',
    postedAt: '1mo ago',
    contract: 'Part Time',
    location: 'Worldwide',
    languages: ['JavaScript'],
    tools: ['React', 'Sass'],
    overview:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis velit ipsum temporibus doloremque itaque quo corrupti similique beatae cum repellendus quasi explicabo odit dolore modi culpa atque, quia quas. Sint!',
    qualifications: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    ],
    salaryStart: 60000,
    salaryEnd: 100000,
    hours: '8am - 5pm',
    responsibilities: [
      'Collaborating with management, departments and customers to identify end-user requirements and specifications',
      'Designing algorithms and flowcharts to create new software programs and systems',
      'Producing efficient and elegant code based on requirements',
      'Testing and deploying programs and applications',
      'Troubleshooting, debugging, maintaining and improving existing software',
      'Compiling and assessing user feedback to improve software performance',
      'Observing user feedback to recommend improvements to existing software products',
      'Developing technical documentation to guide future software development projects',
    ],
    remarks:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolorum, alias maiores aliquam placeat a mollitia inventore atque non numquam consectetur repudiandae sit officia, recusandae sint quisquam aut exercitationem vero.',
  },
];

export default jobs;
